server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowedMethods: GET,POST,PUT,DELETE,PATCH,OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
