server.port=0

application-title=Notification-Service

spring.application.name=notification-service

spring.config.import=optional:file:../../.env[.properties],optional:configserver:http://localhost:8888/

spring.jpa.properties.hibernate.dialect.storage_engine=
spring.jpa.properties.hibernate.dialect=
spring.jpa.open-in-view=false

spring.cloud.loadbalancer.cache.enabled=true
spring.cloud.loadbalancer.cache.ttl=30

notify.user-id=${NOTIFY_USER_ID:}
notify.api-key=${NOTIFY_API_KEY:}
notify.sender-id=${NOTIFY_SENDER_ID:}
