spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/healio
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}

eureka.instance.prefer-ip-address=true
eureka.client.service-url.default-zone=${EUREKA_URI:http://localhost:8761/eureka}

application-description=AI-powered healthcare application
application-license=MIT Licence
application-version=1.0